# Generated by Django 4.2.7 on 2023-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_capital_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='India@gmail.com', max_length=254),
        ),
    ]
